'use client';

import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  X,
  Copy,
  Check,
  Download,
  FileText,
  RefreshCw,
  AlertCircle,
  FileCode,
  FolderOpen,
  Upload,
} from 'lucide-react';
import { DocumentState } from '../../lib/types';
import { extractDocumentText, estimateTokens } from '../../lib/ai/textExtractor';

interface AiSummarizeModalProps {
  isOpen: boolean;
  onClose: () => void;
  documentState: DocumentState;
  onShowToast: (message: string, type?: 'info' | 'success' | 'warning' | 'error') => void;
  onOpenFile?: (file: File) => void;
  onLoadSample?: (sampleType: 'invoice' | 'resume' | 'contract' | 'certificate' | 'proposal' | 'letter' | 'blank') => void;
}

export const AiSummarizeModal: React.FC<AiSummarizeModalProps> = ({
  isOpen,
  onClose,
  documentState,
  onShowToast,
  onOpenFile,
  onLoadSample,
}) => {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [summaryType, setSummaryType] = useState<'standard' | 'bullet' | 'detailed'>('standard');
  const fileInputRef = React.useRef<HTMLInputElement>(null);

  const hasDocument = documentState.pages && documentState.pages.length > 0;
  const docText = React.useMemo(() => extractDocumentText(documentState), [documentState]);
  const tokenCount = React.useMemo(() => estimateTokens(docText), [docText]);

  const generateSummary = async () => {
    if (!hasDocument || !docText || docText.trim().length === 0) {
      setErrorMsg('Please select or upload a readable PDF document first.');
      return;
    }

    setIsLoading(true);
    setErrorMsg(null);

    try {
      const response = await fetch('/api/ai/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          documentText: docText,
          fileName: documentState.fileName || 'document.pdf',
          length: summaryType,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate summary');
      }

      setSummary(data.summary || 'No summary could be generated.');
      onShowToast('Summary generated successfully!', 'success');
    } catch (err: any) {
      console.error('Summary error:', err);
      setErrorMsg(err.message || 'Failed to generate summary. Please check your AI API key.');
    } finally {
      setIsLoading(false);
    }
  };

  // Auto-generate summary on open if document is present and not already generated
  useEffect(() => {
    if (isOpen && hasDocument && !summary && !isLoading && !errorMsg) {
      generateSummary();
    }
  }, [isOpen, hasDocument]);

  const handleCopy = () => {
    if (!summary) return;
    navigator.clipboard.writeText(summary);
    setIsCopied(true);
    onShowToast('Summary copied to clipboard', 'info');
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    if (!summary) return;
    const baseName = (documentState.fileName || 'document').replace(/\.[^/.]+$/, '');
    const mdContent = `# AI Executive Summary: ${documentState.fileName}\n*Generated by PDFly & Claude Sonnet on ${new Date().toLocaleDateString()}*\n\n---\n\n${summary}`;
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${baseName}_summary.md`;
    a.click();
    URL.revokeObjectURL(url);
    onShowToast('Markdown summary downloaded', 'success');
  };

  const handleDownloadText = () => {
    if (!summary) return;
    const baseName = (documentState.fileName || 'document').replace(/\.[^/.]+$/, '');
    const txtContent = `AI EXECUTIVE SUMMARY: ${documentState.fileName}\nGenerated by PDFly & Claude Sonnet\nDate: ${new Date().toLocaleString()}\n\n========================================\n\n${summary}`;
    const blob = new Blob([txtContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${baseName}_summary.txt`;
    a.click();
    URL.revokeObjectURL(url);
    onShowToast('Plain text summary downloaded', 'success');
  };

  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content ai-modal-card"
        style={{ maxWidth: '680px' }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div className="tool-card-icon" style={{ background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', width: '36px', height: '36px' }}>
              <Sparkles size={18} />
            </div>
            <div>
              <h3 className="modal-title">AI Document Summary</h3>
              <p className="modal-subtitle">
                {documentState.fileName || 'Document'} ({documentState.pageCount} pages, ~{tokenCount.toLocaleString()} tokens)
              </p>
            </div>
          </div>
          <button className="nav-btn" onClick={onClose} title="Close">
            <X size={18} />
          </button>
        </div>

        {/* Hidden file input */}
        <input
          type="file"
          ref={fileInputRef}
          accept="application/pdf,.pdf"
          style={{ display: 'none' }}
          onChange={(e) => {
            const f = e.target.files?.[0];
            if (f && onOpenFile) {
              onOpenFile(f);
            }
          }}
        />

        {/* Modal Body */}
        <div className="modal-body" style={{ maxHeight: '60vh', overflowY: 'auto' }}>
          {!hasDocument ? (
            <div style={{ textAlign: 'center', padding: '36px 20px' }}>
              <div
                style={{
                  width: '52px',
                  height: '52px',
                  borderRadius: '14px',
                  background: 'linear-gradient(135deg, #ec4899 0%, #f43f5e 100%)',
                  display: 'inline-flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: '#ffffff',
                  marginBottom: '14px',
                  boxShadow: '0 8px 20px rgba(236, 72, 153, 0.3)',
                }}
              >
                <FolderOpen size={26} />
              </div>
              <h4 style={{ fontSize: '17px', fontWeight: '700', marginBottom: '8px', color: 'var(--text-primary)' }}>
                Please select or upload a PDF
              </h4>
              <p style={{ fontSize: '13px', color: 'var(--text-secondary)', maxWidth: '380px', margin: '0 auto 20px', lineHeight: '1.5' }}>
                To generate an executive summary, AI needs a PDF document to read and synthesize.
              </p>

              {onOpenFile && (
                <button
                  type="button"
                  className="btn-primary"
                  style={{
                    padding: '10px 22px',
                    fontSize: '13.5px',
                    margin: '0 auto 18px',
                    background: 'linear-gradient(135deg, #ec4899 0%, #f43f5e 100%)',
                  }}
                  onClick={() => fileInputRef.current?.click()}
                >
                  <Upload size={16} />
                  <span>Choose PDF Document</span>
                </button>
              )}

              {onLoadSample && (
                <div style={{ marginTop: '10px', borderTop: '1px solid var(--border-subtle)', paddingTop: '16px' }}>
                  <span style={{ fontSize: '11.5px', color: 'var(--text-muted)', display: 'block', marginBottom: '8px' }}>
                    Or summarize a sample template:
                  </span>
                  <div style={{ display: 'flex', gap: '8px', justifyContent: 'center', flexWrap: 'wrap' }}>
                    <button className="sample-chip" onClick={() => onLoadSample('contract')}>
                      ⚖️ NDA Contract
                    </button>
                    <button className="sample-chip" onClick={() => onLoadSample('invoice')}>
                      📄 Invoice
                    </button>
                    <button className="sample-chip" onClick={() => onLoadSample('resume')}>
                      📝 Resume
                    </button>
                  </div>
                </div>
              )}
            </div>
          ) : isLoading ? (
            <div className="ai-loading-state">
              <div className="ai-typing-indicator" style={{ marginBottom: '12px' }}>
                <span className="dot" />
                <span className="dot" />
                <span className="dot" />
              </div>
              <h4 style={{ fontSize: '15px', fontWeight: '700', color: 'var(--text-primary)' }}>
                Synthesizing document with AI Intelligence...
              </h4>
              <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '4px' }}>
                Extracting core arguments, financial metrics, and executive takeaways.
              </p>
            </div>
          ) : errorMsg ? (
            <div className="ai-error-banner">
              <AlertCircle size={20} />
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: '600', marginBottom: '2px' }}>Failed to summarize</div>
                <div style={{ fontSize: '12.5px' }}>{errorMsg}</div>
              </div>
              <button className="btn-secondary" onClick={generateSummary} style={{ padding: '4px 10px' }}>
                <RefreshCw size={13} />
                <span>Retry</span>
              </button>
            </div>
          ) : summary ? (
            <div className="ai-summary-content">
              {summary.split('\n').map((line, idx) => {
                if (line.startsWith('### ') || line.startsWith('## ') || line.startsWith('# ')) {
                  return (
                    <h4 key={idx} className="ai-summary-heading">
                      {line.replace(/^#+\s*/, '')}
                    </h4>
                  );
                }
                if (line.startsWith('- ') || line.startsWith('* ') || line.startsWith('• ')) {
                  return (
                    <li key={idx} className="ai-summary-bullet">
                      {line.replace(/^[-*•]\s*/, '')}
                    </li>
                  );
                }
                if (line.startsWith('**') && line.endsWith('**')) {
                  return (
                    <p key={idx} style={{ fontWeight: '700', color: 'var(--text-primary)', marginTop: '10px' }}>
                      {line.replace(/\*\*/g, '')}
                    </p>
                  );
                }
                return line ? (
                  <p key={idx} className="ai-summary-paragraph">
                    {line}
                  </p>
                ) : (
                  <div key={idx} style={{ height: '6px' }} />
                );
              })}
            </div>
          ) : null}
        </div>

        {/* Modal Footer */}
        <div className="modal-footer" style={{ justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              className="btn-secondary"
              onClick={generateSummary}
              disabled={isLoading || !hasDocument}
              title={!hasDocument ? 'Please select a PDF document first' : 'Regenerate summary'}
            >
              <RefreshCw size={14} className={isLoading ? 'spin-icon' : ''} />
              <span>Regenerate</span>
            </button>
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              className="btn-secondary"
              onClick={handleCopy}
              disabled={!summary || isLoading}
            >
              {isCopied ? <Check size={14} /> : <Copy size={14} />}
              <span>{isCopied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              className="btn-secondary"
              onClick={handleDownloadMarkdown}
              disabled={!summary || isLoading}
            >
              <FileCode size={14} />
              <span>Export .MD</span>
            </button>
            <button
              className="btn-primary"
              onClick={handleDownloadText}
              disabled={!summary || isLoading}
            >
              <Download size={14} />
              <span>Download .TXT</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
